baseURL = "http://petemcdonald.co/"
languageCode = "en-us"
title = "Pete McDonald"
theme = "yinyang"
DefaultContentLanguage = "en"
googleAnalytics = "UA-145441864-1"

ignoreFiles = ["content/en/two-outdoor-centres.md"]

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[[params.socials]]
  name = "About Me"
  link = "about"

[author]
  name = "Pete McDonald"
  homepage = "https://petemcdonald.co/"

[markup.goldmark.renderer]
  unsafe= true

# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true